#!/bin/bash

echo "🚀 Direct Push to GitHub"
echo "========================"
echo ""
echo "Please run this command in your Shell, replacing YOUR_TOKEN with your actual GitHub token:"
echo ""
echo "git push https://blanddes37-2:YOUR_TOKEN@github.com/blanddes37-2/DealProgressionTracker.git main"
echo ""
echo "Example (don't copy this, use your real token):"
echo "git push https://blanddes37-2:ghp_abc123xyz789@github.com/blanddes37-2/DealProgressionTracker.git main"
echo ""
echo "IMPORTANT:"
echo "- Replace YOUR_TOKEN with your actual GitHub Personal Access Token"
echo "- The token should start with 'ghp_'"
echo "- Make sure your token has 'repo' permissions"
echo ""
echo "If you get an error about the repository not existing:"
echo "1. Go to https://github.com/blanddes37-2"
echo "2. Create a new repository named 'DealProgressionTracker'"
echo "3. Make it Public (don't initialize with README)"
echo "4. Try the push command again"